### ISSUE TITLE
Getting error `e.xr.getEnvironmentBlendMode is not a function`

### ISSUE THREAD

**Issue by lislis** [akbartus/A-Frame-Component-Postprocessing#3]
Hey @akbartus thank you for working on this!
I wanted to try some effects in my own project but ran into that is also thrown on your demo page!
In Firefox and Safari I get `Uncaught TypeError: xr.getEnvironmentBlendMode is not a function`. In Chrome it seems to work. Do you think there is an easy fix for that?

**Comment by akbartus** [comment]
@lislis thanks for your comment. Unfortunately this feature is not supported in Firefox and Safari. In order for post-processing to work on them you need to uncomment the following lines in aframe.min.js file:

```
// const environmentBlendMode = xr.getEnvironmentBlendMode();
              // switch (environmentBlendMode) {
              //   case "opaque":
              //     forceClear = true;
              //     break;
              //   case "additive":
              //     state.buffers.color.setClear(0, 0, 0, 1, premultipliedAlpha);
              //     forceClear = true;
              //     break;
              //   case "alpha-blend":
              //     state.buffers.color.setClear(0, 0, 0, 0, premultipliedAlpha);
              //     forceClear = true;
              //     break;
              // }
```
and this:
```
       // this.getEnvironmentBlendMode = function () {
              //   if (session !== null) {
              //     return session.environmentBlendMode;
              //   }
              // };
```
Then it should work. I updated the demo with these changes.

**Comment by lislis** [comment]
Super helpful, thanks!
